name: Save to Firestore

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

jobs:
  save-message:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Configure Google Credentials
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      run: |
        echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" > /tmp/credentials.json
        export GOOGLE_APPLICATION_CREDENTIALS=/tmp/credentials.json

    - name: Run Python script
      run: python save_to_firestore.py
